- hosts: localhost
  connection: local
  become: true
  pre_tasks:
          - name: update repository
            dnf:
                    update_cache: yes
            when_change: false

  tasks:
          - include: tasks/users.yml
          - include: tasks/package.yml
          - include: tasks/cron.yml
